name: Build Action
on:
  push:
    branches:
      - Build
jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        unityVersion:
          - 2021.3.16f1
        targetPlatform: 
          - StandaloneWindows64
        projectName:
          - BuildActions
    steps:
      #Checking out the repo 
      - name: Checkout repo 
        uses: actions/checkout@v2
        with:
          lfs: false

      #Testing if caching is working 
      - name: run
        run: ls

      #Caching
      - name: Caching
        uses: actions/cache@v2
        with:
          path: ./Library
          key: Library-${{matrix.projectName}}-${{matrix.targetPlatform}}
          restore-keys: |
            Library-${{matrix.projectName}}-
            Library-

      #Making the build. 
      - name: Unity Builder
        uses: game-ci/unity-builder@v2.0-alpha-6
        env:
          UNITY_LICENSE: ${{ secrets.UNITY_LICENSE }}
        with:
          unityVersion: ${{matrix.unityVersion}}
          targetPlatform: ${{matrix.targetPlatform}}

      #Uploading the build to github.
      - name: Uploading the build
        uses: actions/upload-artifact@v2
        with:
          name: Build
          path: build
